In [120]:
import pandas as pd

In [121]:
# import data into data frame and Manipulate it

In [122]:
import pandas as pd
 
# creating a data frame
df = pd.read_csv("depression_anxiety_data.csv")
print(df.head())

   id  school_year  age  gender        bmi          who_bmi  phq_score  \
0   1            1   19    male  33.333333  Class I Obesity          9
1   2            1   18    male  19.841270           Normal          8
2   3            1   19    male  25.102391       Overweight          8
3   4            1   18  female  23.738662           Normal         19
4   5            1   18    male  25.617284       Overweight          6

  depression_severity depressiveness suicidal depression_diagnosis  \
0                Mild          False    False                False
1                Mild          False    False                False
2                Mild          False    False                False
3   Moderately severe           True     True                False
4                Mild          False    False                False

  depression_treatment  gad_score anxiety_severity anxiousness  \
0                False         11         Moderate        True
1                False          5             Mild       False
2                False          6             Mild       False
3                False         15           Severe        True
4                False         14         Moderate        True

  anxiety_diagnosis anxiety_treatment  epworth_score sleepiness
0             False             False            7.0      False
1             False             False           14.0       True
2             False             False            6.0      False
3             False             False           11.0       True
4             False             False            3.0      False

In [123]:
from pandas import DataFrame
df = DataFrame (data)
df

,id,school_year,Ages,gender,bmi,who_bmi,phq_score,depression_severity,depressiveness,suicidal,depression_diagnosis,depression_treatment,gad_score,anxiety_severity,anxiousness,anxiety_diagnosis,anxiety_treatment,epworth_score,sleepiness
0,1,1,19,male,33.333333,Class I Obesity,9,Mild,False,False,False,False,11,Moderate,True,False,False,7.0,False
1,2,1,18,male,19.841270,Normal,8,Mild,False,False,False,False,5,Mild,False,False,False,14.0,True
2,3,1,19,male,25.102391,Overweight,8,Mild,False,False,False,False,6,Mild,False,False,False,6.0,False
3,4,1,18,female,23.738662,Normal,19,Moderately severe,True,True,False,False,15,Severe,True,False,False,11.0,True
4,5,1,18,male,25.617284,Overweight,6,Mild,False,False,False,False,14,Moderate,True,False,False,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
778,779,4,24,female,21.096191,Normal,6,Mild,False,False,False,False,1,None-minimal,False,False,False,3.0,False
779,780,4,22,male,25.308642,Overweight,4,None-minimal,False,False,False,False,6,Mild,False,False,False,3.0,False
780,781,4,22,male,22.720438,Normal,2,None-minimal,False,False,False,False,5,Mild,False,False,False,4.0,False
781,782,4,22,female,23.033168,Normal,17,Moderately severe,True,False,False,False,19,Severe,True,False,False,15.0,True
782,783,4,22,male,22.598140,Normal,6,Mild,False,False,False,False,6,Mild,False,False,False,0.0,False

In [124]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 783 entries, 0 to 782
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   id                    783 non-null    int64
 1   school_year           783 non-null    int64
 2   Ages                  783 non-null    int64
 3   gender                783 non-null    object
 4   bmi                   783 non-null    float64
 5   who_bmi               783 non-null    object
 6   phq_score             783 non-null    int64
 7   depression_severity   779 non-null    object
 8   depressiveness        780 non-null    object
 9   suicidal              782 non-null    object
 10  depression_diagnosis  782 non-null    object
 11  depression_treatment  779 non-null    object
 12  gad_score             783 non-null    int64
 13  anxiety_severity      783 non-null    object
 14  anxiousness           777 non-null    object
 15  anxiety_diagnosis     779 non-null    object
 16  anxiety_treatment     781 non-null    object
 17  epworth_score         775 non-null    float64
 18  sleepiness            775 non-null    object
dtypes: float64(2), int64(5), object(12)
memory usage: 116.4+ KB

(783, 19)

In [125]:
df.tail(5)

,id,school_year,Ages,gender,bmi,who_bmi,phq_score,depression_severity,depressiveness,suicidal,depression_diagnosis,depression_treatment,gad_score,anxiety_severity,anxiousness,anxiety_diagnosis,anxiety_treatment,epworth_score,sleepiness
778,779,4,24,female,21.096191,Normal,6,Mild,False,False,False,False,1,None-minimal,False,False,False,3.0,False
779,780,4,22,male,25.308642,Overweight,4,None-minimal,False,False,False,False,6,Mild,False,False,False,3.0,False
780,781,4,22,male,22.720438,Normal,2,None-minimal,False,False,False,False,5,Mild,False,False,False,4.0,False
781,782,4,22,female,23.033168,Normal,17,Moderately severe,True,False,False,False,19,Severe,True,False,False,15.0,True
782,783,4,22,male,22.598140,Normal,6,Mild,False,False,False,False,6,Mild,False,False,False,0.0,False

In [126]:
df[1:6]

,id,school_year,Ages,gender,bmi,who_bmi,phq_score,depression_severity,depressiveness,suicidal,depression_diagnosis,depression_treatment,gad_score,anxiety_severity,anxiousness,anxiety_diagnosis,anxiety_treatment,epworth_score,sleepiness
1,2,1,18,male,19.841270,Normal,8,Mild,False,False,False,False,5,Mild,False,False,False,14.0,True
2,3,1,19,male,25.102391,Overweight,8,Mild,False,False,False,False,6,Mild,False,False,False,6.0,False
3,4,1,18,female,23.738662,Normal,19,Moderately severe,True,True,False,False,15,Severe,True,False,False,11.0,True
4,5,1,18,male,25.617284,Overweight,6,Mild,False,False,False,False,14,Moderate,True,False,False,3.0,False
5,6,1,18,male,22.129740,Normal,3,None-minimal,False,False,False,False,2,None-minimal,False,False,False,2.0,False

In [128]:
#clean data
df.isnull().sum()

id                      0
school_year             0
Ages                    0
gender                  0
bmi                     0
who_bmi                 0
phq_score               0
depression_severity     4
depressiveness          3
suicidal                1
depression_diagnosis    1
depression_treatment    4
gad_score               0
anxiety_severity        0
anxiousness             6
anxiety_diagnosis       4
anxiety_treatment       2
epworth_score           8
sleepiness              8
dtype: int64

In [131]:
df.fillna(0)

,id,school_year,Ages,gender,bmi,who_bmi,phq_score,depression_severity,depressiveness,suicidal,depression_diagnosis,depression_treatment,gad_score,anxiety_severity,anxiousness,anxiety_diagnosis,anxiety_treatment,epworth_score,sleepiness
0,1,1,19,male,33.333333,Class I Obesity,9,Mild,False,False,False,False,11,Moderate,True,False,False,7.0,False
1,2,1,18,male,19.841270,Normal,8,Mild,False,False,False,False,5,Mild,False,False,False,14.0,True
2,3,1,19,male,25.102391,Overweight,8,Mild,False,False,False,False,6,Mild,False,False,False,6.0,False
3,4,1,18,female,23.738662,Normal,19,Moderately severe,True,True,False,False,15,Severe,True,False,False,11.0,True
4,5,1,18,male,25.617284,Overweight,6,Mild,False,False,False,False,14,Moderate,True,False,False,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
778,779,4,24,female,21.096191,Normal,6,Mild,False,False,False,False,1,None-minimal,False,False,False,3.0,False
779,780,4,22,male,25.308642,Overweight,4,None-minimal,False,False,False,False,6,Mild,False,False,False,3.0,False
780,781,4,22,male,22.720438,Normal,2,None-minimal,False,False,False,False,5,Mild,False,False,False,4.0,False
781,782,4,22,female,23.033168,Normal,17,Moderately severe,True,False,False,False,19,Severe,True,False,False,15.0,True
782,783,4,22,male,22.598140,Normal,6,Mild,False,False,False,False,6,Mild,False,False,False,0.0,False

In [129]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
778    False
779    False
780    False
781    False
782    False
Length: 783, dtype: bool

In [88]:
print(df['id'].isnull())

0      False
1      False
2      False
3      False
4      False
       ...
778    False
779    False
780    False
781    False
782    False
Name: id, Length: 783, dtype: bool

In [89]:
df.columns

Index(['id', 'school_year', 'age', 'gender', 'bmi', 'who_bmi', 'phq_score',
       'depression_severity', 'depressiveness', 'suicidal',
       'depression_diagnosis', 'depression_treatment', 'gad_score',
       'anxiety_severity', 'anxiousness', 'anxiety_diagnosis',
       'anxiety_treatment', 'epworth_score', 'sleepiness'],
      dtype='object')

In [95]:
df2 = df.rename(columns={'age':'Ages'}, inplace = True)

In [97]:
df.columns

Index(['id', 'school_year', 'Ages', 'gender', 'bmi', 'who_bmi', 'phq_score',
       'depression_severity', 'depressiveness', 'suicidal',
       'depression_diagnosis', 'depression_treatment', 'gad_score',
       'anxiety_severity', 'anxiousness', 'anxiety_diagnosis',
       'anxiety_treatment', 'epworth_score', 'sleepiness'],
      dtype='object')

In [134]:
df2 =df.groupby(['Ages']).sum()
print(df2)

         id  school_year          bmi  phq_score  gad_score  epworth_score
Ages
18    13089          122  2629.106070        790        786          688.0
19    53358          306  4691.424442       1560       1527         1349.0
20    53098          302  3451.978906       1095       1009          888.0
21    87602          498  3601.560556       1032        945          993.0
22    65770          368  2406.916948        703        675          616.0
23    18067           98   775.799669        189        201          185.0
24     9166           51   456.660210        127         99          131.0
25     1982           11    96.971769         20         31           35.0
26     2090           12    99.381036         24         19           28.0
27      599            3    28.076319          5          6            3.0
28      506            3    29.352355         10          9           13.0
30      743            4    24.691358          5          8            3.0
31      866            5    46.357517         18         18           10.0